apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/bob-db.yaml
    - ./components/bob-cache.yaml
    - ./components/bob-queue.yaml
    - ./components/bob-web.yaml