version: 2
updates:
- package-ecosystem: "npm"
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: "hotfix/dependabot"
- package-ecosystem: github-actions
  directory: .github/
  schedule:
    interval: daily