version: "3.8"
services:
  app:
    command: sh -c 'yarn dev'
    platform: linux/amd64
    build:
      context: .
      target: dev
    working_dir: /app
    volumes: []
    ports:
      - 3000:3000
      - 7007:7007
    expose:
      - 3000
      - 7007
    environment:
      - ARGOCD_AUTH_TOKEN=$ARGOCD_AUTH_TOKEN
      - AUTH_GITHUB_CLIENT_ID=$AUTH_GITHUB_CLIENT_ID
      - AUTH_GITHUB_CLIENT_SECRET=$AUTH_GITHUB_CLIENT_SECRET
      - ENV=development
      - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
      - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
      - GRAFANA_TOKEN=$GRAFANA_TOKEN
      - K8S_TOKEN=$K8S_TOKEN
      - K8S_URL=$K8S_URL
      - PGDATABASE=backstage
      - POSTGRES_DATABASE=backstage
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - SONARQUBE_TOKEN=$SONARQUBE_TOKEN
      - TECHDOCS_BUCKET=$TECHDOCS_BUCKET
      # - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      # - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      # - AWS_REGION=$AWS_REGION
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backstage
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: {}
