app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: https://www.diegoluisi.eti.br

backend:
  baseUrl: https://www.diegoluisi.eti.br
  listen:
    port: 443
  database:
    # client: better-sqlite3
    # connection: ':memory:'
    # config options: https://node-postgres.com/api/client
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    # Refer to Tarn docs for default values on PostgreSQL pool configuration - https://github.com/Vincit/tarn.js
    knexConfig:
      pool:
        min: 3
        max: 12
        acquireTimeoutMillis: 60000
        idleTimeoutMillis: 60000      