# This workflow uses actions that are not certified by GitHub.
# São fornecidas por terceiros e regidas por
# termos de serviço, política de privacidade e suporte separados
# documentação.

name: Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  vars:
    name: Setup environment variables
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
          else
            echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"
          fi
      - run: echo "${{ steps.vars.outputs.tag }}"

  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - vars
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd app/
          yarn add --cwd packages/app @backstage/plugin-sonarqube
          yarn install --frozen-lockfile
          yarn tsc
          yarn build
          docker image build . -f packages/backend/Dockerfile --tag diegoluisi/backstage:${{ needs.vars.outputs.tag }}
          docker push diegoluisi/backstage:${{ needs.vars.outputs.tag }}

  deploy:
    name: GitOps Deploy

    runs-on: ubuntu-latest
    needs:
      - vars
      - build-and-push

    steps:
    - name: Set Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.9.4"

    - name: Clone Argo Repository
      run: git clone https://${REPO_TOKEN}@github.com/diegoluisi/argo.git .
      env:
        REPO_TOKEN: ${{secrets.ACCESS_TOKEN_GITHUB}}

    - name: Update Backstage Tag Image
      run: |
        cd apps/backstage/overlays/prd
        kustomize edit set image diegoluisi/backstage:${{ needs.vars.outputs.tag }}

    - name: Commit Changes
      run: |
        git version
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m ":robot: [GitHub Action] Set new image tag to https://github.com/diegoluisi/backstage/commit/${{ needs.vars.outputs.tag }}"

    - name: Push changes
      run: git push
